# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ede52df96d4e8b9552709e042c8496e"
name = "Copié-Collé Pro Test\r"
application_url = "https://mockups-shopify-69z6.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://mockups-shopify-69z6.vercel.app/api/auth" ]
